### ISSUE TITLE
core_genomes.fas

### ISSUE THREAD

**Issue by nbawe** [jizhang-nz/fast-GeP#1]
Hello, does file "core_genomes.fas" include loci form
 (1) number of shared-loci 
or 
(2) number of shared-loci that was used to construct distance/difference matrix?

I think it contains the (2) - am I right?

Thanks in advance.

**Comment by jizhang-nz** [comment]
Yes you are right. 
So-called "shared-loci" also includes genes of hypothetical duplication, which are shared by all the isolates but are not differentiated between ortholog and paralog thus not used to construct distance/difference matrix in the later analysis.

**Comment by nbawe** [comment]
Thanks!

**Comment by nbawe** [comment]
@jizhang-nz the algorithm is absolutely fantastic  surpassing GeP by lightyears - so brilliantly fast!

**Comment by jizhang-nz** [comment]
I'm glad that you find it useful!
