### ISSUE TITLE
GeP vs fast-GeP

### ISSUE THREAD

**Issue by nbawe** [jizhang-nz/fast-GeP#11]
Hi could you briefly explain differences in algorithm used in GeP (gene-by-gene) vs fast-GeP (genome-by-genome) - how does it make fast-GeP so much faster than GeP?

**Comment by jizhang-nz** [comment]
The genome-by-genome approach was inspired by the Overall Planning Methods (统筹法 in Chinese), which was proposed by Loo-Keng Hua.
It can be found in the book _[Popularizing Mathematical Methods in the People’s Republic of China](https://link.springer.com/book/10.1007/978-1-4684-6757-4#about)_
Following the roles of the Overall Planning Methods is the reason that fast-GeP is fast.
