### ISSUE TITLE
Output differences!

### ISSUE THREAD

**Issue by nbawe** [jizhang-nz/fast-GeP#12]
I have run into some issues with output discrepancies. I have two genomes both have annotations (RAST) I ran two runs as follows:

1) First run:
*Genome 1, Genome 2 with annotated Genome 1 as reference.
*RESULT: 5 allele differences.

2) Second run:
*Genome 1, Genome 2 with annotatated Genome 2 as reference.
*RESULT: 4 allele differences.

Is it possible or am I doing something wrong?

**Comment by nbawe** [comment]
I tested with prokka annotations with two runs - no discrepancies in the results (both has 4 allele differences).

Also deleted annotations from RAST and re-annotated both, but still discrepancies as previously mentioned.

**Comment by jizhang-nz** [comment]
The program fast-GeP uses _ad hoc_ wgMLST scheme, i.e. it uses the annotation of the reference genome to create a wgMLST scheme for the analysis.

For that reason, if the annotations (total number of CDS, ranges of CDS, etc.) of Genome 1 and Genome 2 were different, the two wgMLST runs would be using two different wgMLST schemes, which could result in differences in the final results.

You might want to take a look at the definitions of the fifth locus in the RAST annotations of Genome 1 and Genome 2. 

Maybe in one of the genomes the gene is truncated?

**Comment by nbawe** [comment]
Thank you! I also ran chewBBACA to assess the cgMLST alleles and 5 allele differences was also observed using chewBBACA.
