### ISSUE TITLE
Broken link in the generated html_XXXXXXXXXX comparison html files.

### ISSUE THREAD

**Issue by maesaar** [jizhang-nz/fast-GeP#13]
Hello,

there seems to be a broken link named `index` generated in the comparison html files in the `html_XXXXXXXXX` folder. The link should direct back to the `output_XXXXXXXXXX/difference_matrix.html`. Instead the link directs to the report.html which is not generated [(it occurres in the fast-GeP.pl line 1164)](https://github.com/jizhang-nz/fast-GeP/blob/9966e45d3ecf7ee7e824dad693521d3f6aa04059/fast-GeP.pl#L1164). The correct linking should direct to the difference_matrix.html.

**Comment by jizhang-nz** [comment]
Hi mmaesaar,
Thanks for reporting this. It was indeed a bug. Good catch!
It is now fixed. If there is any problem, please let me know. Thank you.
Regards,
Ji
