### ISSUE TITLE
Question: clonalframe.dat and core_genomes.fas used with ClonalFrameML

### ISSUE THREAD

**Issue by nbawe** [jizhang-nz/fast-GeP#14]
Hello @jizhang-nz!

I have used fast-GeP using two outputs with ClonalFrameML.

1) when using concatenated fasta e.g. core_genomes.fas I get the following:
`Read 7 sequences of length 1487811 sites from core_genomes.fas`

2) then Xavier Didelot said that xmfa is more suitable with ClonalFrameML and when using xmfa e.g. clonalframe.dat. I get the following:
`Read 7 sequences of length 3180811 sites from clonalframe.dat`

Do you have any idea why I  get different number of sites?

**Comment by nbawe** [comment]
I also asked the question in ClonalFrameML GitHub [issue #118](https://github.com/xavierdidelot/ClonalFrameML/issues/118)

**Comment by jizhang-nz** [comment]
Hi nbawe,
I don't know why did ClonalFrameML report different numbers of sites on different formats of the same sequence alignments. I believe it's something the authors of the ClonalFrameML could answer.
Cheers,
Ji

**Comment by nbawe** [comment]
Thanks @jizhang-nz

**Comment by jizhang-nz** [comment]
According to the author of ClonalFrameML: 

_xavierdidelot commented 1 hour ago
That's because when working with a xmfa file, ClonalFrameML inserts 1000bp blank regions between each consecutive block._

**Comment by nbawe** [comment]
Thanks
