### ISSUE TITLE
Difference matrix creation!

### ISSUE THREAD

**Issue by maesaar** [jizhang-nz/fast-GeP#15]
@jizhang-nz how is difference matrix created? 

Does the difference matrix include only loci that are present 100% of isolates? I mean how are missing loci treated are they completely disregarded or pairwise excluded?

I hope my question is clear.

**Comment by maesaar** [comment]
To clarify are missing loci completely excluded from the analysis (eg if missing in one isolate then the loci is removed from analysis for all isolates) or missing loci are handled pairwise (eg if missing in one then comparing the one isolate with other where it is present then loci is excluded but when present in two isolates then it is included)?

**Comment by maesaar** [comment]
Ok supplementary material of the manuscript has an explanation! They are excluded! So the distance matrix has only loci present in all isolates.

**Comment by maesaar** [comment]
@jizhang-nz could you confirm that I understand it correctly?

**Comment by jizhang-nz** [comment]
Yes, allele distance can only be calculated from the loci shared by all the isolates.
