### ISSUE TITLE
Difference_matrix.html file problem.

### ISSUE THREAD

**Issue by nbawe** [jizhang-nz/fast-GeP#2]
I ran analysis and everything was ok, but when I open difference_matrix.html file there are

Fast-GeP analysis started at Mon Oct 29 22:40:58 EET 2018 .
XXXXXXXXXX.gbk was used as reference genome.
Allele sequences were searched with BLAST+ (identity threshold >= 80).
Fast-GeP analysis started at Mon Oct 29 22:42:02 EET 2018 .
XXXXXXXXXX.gbk was used as reference genome.
Allele sequences were searched with BLAST+ (identity threshold >= 80).

Why it has first three lines two times and with different start time, do I need to rerun the analyses?

Thanks

**Comment by jizhang-nz** [comment]
Hi,
It was likely caused by the temporary files that created from previous (unsuccessful) run. 
Please make sure that all the temporary files (filename extension *.tmp) are removed from the working directory before starting a new run.
Cheers,
Ji

**Comment by nbawe** [comment]
Yes I tested again and that was exactly the issue - If folder wasn’t empty then the header was duplicated
