### ISSUE TITLE
Latest commit

### ISSUE THREAD

**Issue by nbawe** [jizhang-nz/fast-GeP#3]
Hello - I am just about to publish paper using fast-gep (ran analyses in november), but now I see there is new commit (identity% threshold in complementary search added). I looked the code but don't understand what does it do? Should i re-run analysis? 

Thank you for quick response!

**Comment by jizhang-nz** [comment]
Hi,
Thank you for your question. Identity% threshold in complementary search is a feature that should have been in all the earlier versions. I found that a too divergent allele sequence were likely to be either a paralogue or a recombinant gene, thus should be removed from the final allele profiling. I expect that the latest addition might improve slightly the accuracy of finding the orthologue in some cases, but I do not believe it would change the allele distances of the isolates dramatically, if they would be changed at all.

**Comment by nbawe** [comment]
Thank you! I had C. jejuni isolates belonging to one ST. So I expect them not to bee too divergent.
