### ISSUE TITLE
Could fast-Gep  run analysis with exiting wgMLST scheme ?

### ISSUE THREAD

**Issue by hngyou** [jizhang-nz/fast-GeP#4]
Hi,
I am using fast-Gep and Gep, I think they are both very good tools. But would you tell me if fast-Gep could run analysis with exiting wgMLST scheme ? and how? I have noticed  that Gep has that option "-o: Run the analysis with exiting wgMLST scheme", fast-Gep hasn't.
Thank you.

**Comment by jizhang-nz** [comment]
Thank you for your appreciation and question. 
Yes indeed running on existing wgMLST scheme is a feature that has not been incorporated into the current version of  fast-GeP. It might be something worth to be considered in the making of next version.
Cheers.

**Comment by hngyou** [comment]
Thanks for your reply.  Wish we can use the next version soon!
